import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// this should import it fine, we are on the server
import MyApi from "@/api/base";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // fine as well
  const myClientOnServerSinceThisIsServerComponent = new MyApi();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
